In [1]:
import pandas as pd
import seaborn as sns

from sklearn.preprocessing import LabelEncoder

In [2]:
df=sns.load_dataset('tips')

In [3]:
from sklearn.preprocessing import LabelEncoder
encoder_time= LabelEncoder( )

encoded_data=encoder_time.fit_transform(df['time'])

In [4]:
print('classes',encoder_time.classes_)

classes ['Dinner' 'Lunch']

In [5]:
for category,number in zip (encoder_time.classes_, range(len(encoder_time.classes_))):
    print(category,"-----------",number)

Dinner ----------- 0
Lunch ----------- 1

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
encoder_day= LabelEncoder( )

encoded_day_data=encoder_day.fit_transform(df['day'])

In [8]:
encoder_day= LabelEncoder( )

encoded_day_data=encoder_day.fit_transform(df['day'])

In [9]:
print('classes',encoder_day.classes_)

classes ['Fri' 'Sat' 'Sun' 'Thur']

In [10]:
for category,number in zip (encoder_day.classes_, range(len(encoder_day.classes_))):
    print(category,"-----------",number)

Fri ----------- 0
Sat ----------- 1
Sun ----------- 2
Thur ----------- 3

In [11]:
from sklearn.preprocessing import OneHotEncoder

In [12]:
encoder_day.inverse_transform([0,1,2,3])

array(['Fri', 'Sat', 'Sun', 'Thur'], dtype=object)

In [13]:
ohe=OneHotEncoder(sparse_output= False)
ohe.fit_transform(df[['sex','smoker']])

array([[1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.]])

In [14]:
ohe=OneHotEncoder(sparse_output= False,drop='first')
ohe_encoder=ohe.fit_transform(df[['sex','smoker']])
ohe_encoder

array([[0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [0., 0.]])

In [15]:
df1=pd.DataFrame(ohe_encoder,columns=ohe.get_feature_names_out())
df1

     sex_Male  smoker_Yes
0         0.0         0.0
1         1.0         0.0
2         1.0         0.0
3         1.0         0.0
4         0.0         0.0
..        ...         ...
239       1.0         0.0
240       0.0         1.0
241       1.0         1.0
242       1.0         0.0
243       0.0         0.0

[244 rows x 2 columns]

In [16]:
pd.concat([df,df1],axis=1)

     total_bill   tip     sex smoker   day    time  size  sex_Male  smoker_Yes
0         16.99  1.01  Female     No   Sun  Dinner     2       0.0         0.0
1         10.34  1.66    Male     No   Sun  Dinner     3       1.0         0.0
2         21.01  3.50    Male     No   Sun  Dinner     3       1.0         0.0
3         23.68  3.31    Male     No   Sun  Dinner     2       1.0         0.0
4         24.59  3.61  Female     No   Sun  Dinner     4       0.0         0.0
..          ...   ...     ...    ...   ...     ...   ...       ...         ...
239       29.03  5.92    Male     No   Sat  Dinner     3       1.0         0.0
240       27.18  2.00  Female    Yes   Sat  Dinner     2       0.0         1.0
241       22.67  2.00    Male    Yes   Sat  Dinner     2       1.0         1.0
242       17.82  1.75    Male     No   Sat  Dinner     2       1.0         0.0
243       18.78  3.00  Female     No  Thur  Dinner     2       0.0         0.0

[244 rows x 9 columns]

In [17]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

In [18]:
power=FunctionTransformer(np.log10)
power.FunctionTransformer

AttributeError: 'FunctionTransformer' object has no attribute 'FunctionTransformer'

In [ ]:
log=FunctionTransformer(np.log)
log.fit_transform(df['tip'])

In [ ]:
log_2=FunctionTransformer(np.log2)
log_2.fit_transform(df['tip'])

In [ ]:
import numpy as np
from sklearn.preprocessing import PowerTransformer

In [ ]:
X = np.array([[-1],[0],[3],[5],[10],[50]])

pt = PowerTransformer(method='yeo-johnson')
X_transformed = pt.fit_transform(X)

print('Original:')
print(X.ravel())

print('\nTransfromed:')
print(np.round(X_transformed.ravel(),3))

print('\nLearned lambda:')
print(pt.lambdas_)

In [ ]:
Y = np.array([[1],[1],[3],[5],[10],[50]])

pt = PowerTransformer(method='box-cox')
Y_transformed = pt.fit_transform(Y)

print('Original:')
print(Y.ravel())

print('\nTransfromed:')
print(np.round(Y_transformed.ravel(),3))

print('\nLearned lambda:')
print(pt.lambdas_)

In [7]:
import pandas as pd
import numpy as np
data= {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Grace', 'Henry', 'Ivy', 'Jack'],
    'Gender': ['Female', 'Male', np.nan, 'Male', 'Female', 'Male', 'Female', 'Male', np.nan, 'Male'],
    'Age': [28, np.nan, 35, 42, 29, 31, np.nan, 40, 24, 36],
    'Department': ['HR', 'IT', 'Finance', 'IT', np.nan, 'Finance', 'HR', 'IT', 'Marketing', 'Marketing'],
    'Salary': [55000, 72000, 68000, np.nan, 61000, 59000, 52000, 85000, np.nan, 64000],
    'City': ['New York', 'Chicago', np.nan, 'Boston', 'New York', 'Chicago', np.nan, 'Boston', 'Chicago', 'New York'],
    'Purchased': ['No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes']
}

df = pd.DataFrame(data)
df

      Name  Gender   Age Department   Salary      City Purchased
0    Alice  Female  28.0         HR  55000.0  New York        No
1      Bob    Male   NaN         IT  72000.0   Chicago       Yes
2  Charlie     NaN  35.0    Finance  68000.0       NaN        No
3    David    Male  42.0         IT      NaN    Boston       Yes
4     Emma  Female  29.0        NaN  61000.0  New York       Yes
5    Frank    Male  31.0    Finance  59000.0   Chicago        No
6    Grace  Female   NaN         HR  52000.0       NaN        No
7    Henry    Male  40.0         IT  85000.0    Boston       Yes
8      Ivy     NaN  24.0  Marketing      NaN   Chicago        No
9     Jack    Male  36.0  Marketing  64000.0  New York       Yes

In [8]:
import pandas as pd

In [9]:
from sklearn.impute import SimpleImputer

In [10]:
imputer= SimpleImputer(strategy='mean')
imputer.fit_transform(df[['Salary']]).flatten()

array([55000., 72000., 68000., 64500., 61000., 59000., 52000., 85000.,
       64500., 64000.])

In [ ]:
imputer=SimpleImputer(strategy='most_frequent',)